#!/bin/bash
# puppet-ramdisk	Init script for running the puppet client daemon
#
# Author:		Christian Flamm <christian.flamm@mercateo.com>
# Description:  	Starts original puppet agent service but mounts a ram disk to puppet's status directory
# Short-Description: 	puppet agent ramstatus
# Provides:		puppet
# Default-Start:     	2 3 4 5
# Default-Stop:      	0 1 6

### END INIT INFO                                                                                                                                          
SIZE=100M
STATE_DIR=/var/lib/puppet/state
TRY_LAZY_UNMOUNT=false

function do_mount() {
	(cd / && mount -o size=${SIZE} -t tmpfs none ${STATE_DIR})
}

function do_umount() {
	OPTS=""
	${TRY_LAZY_UNMOUNT} && OPTS=" --lazy"
	(cd / && umount ${STATE_DIR} ${OPTS})
}

function mount_status() {
	mount | grep ${STATE_DIR}
}

function do_start() {
	do_umount
	do_mount
	mount_status
	service puppet start
}

function do_stop() {
	service puppet stop
	do_umount
	mount_status
}

function do_reload() {
	service puppet reload
}

function do_status() {
	service puppet status
	mount_status
}

function do_restart() {
	do_stop
	do_start
}


case "$1" in
    start)
	do_start
	;;
    stop)
	do_stop
	;;
    reload)
	do_reload
    	;;
    status)
	do_status
	;;
    restart|force-reload)
	do_reload
	;;
  *)
	echo "Usage: $0 {start|stop|status|restart|force-reload|reload}" >&2
	exit 1
	;;
esac
